export const projects = [
  {
    id: 0,
    title: "Lost in Space",
    mainImgOrVideo: "/images/60FPS.mp4",
    images: [
      "/lost-in-space/1.png",
      "/lost-in-space/2.png",
      "/lost-in-space/3.png",
      "/lost-in-space/4.png",
      "/lost-in-space/5.png",
      "/lost-in-space/6.png",
      "/lost-in-space/7.png",
      "/lost-in-space/8.png",
      "/lost-in-space/9.png",
      "/lost-in-space/10.png",
      "/lost-in-space/11.png",
      "/lost-in-space/12.png",
    ],
    overview:
      "We partnered with From The Farm to refresh their brand digitally and visually. We built a custom Shopify site with vintage-inspired design and created realistic 3D packaging renderings, uniting charm and function to connect authentically with customers.",
    description: "Launching creativity beyond limits",
    liveSiteUrl: "https://www.fromthefarmco.com/",
    year: "2025",
  },
  {
    id: 1,
    title: "From the Farm",
    mainImgOrVideo: "/images/ftf.png",
    description: "A2 DAIRY-FREE ICE CREAM",
    liveSiteUrl: "https://www.fromthefarmco.com/",
    year: "2025",
  },
  {
    id: 2,
    title: "Paranano",
    mainImgOrVideo: "/images/paranano.png",
    description: "A bio-technology company",
    liveSiteUrl: "https://www.paranano.com/",
    year: "2025",
  },
  {
    id: 3,
    title: "Good Gummies",
    mainImgOrVideo: "/images/oggg.png",
    description: "Protein, fiver, fun",
    liveSiteUrl: "https://www.goodgummies.com/",
    year: "2025",
  },
  {
    id: 4,
    title: "Free range",
    mainImgOrVideo: "/images/free.png",
    description: "Beef tallow & botanicals in perfect harmony",
    liveSiteUrl: "https://www.freerange.com/",
    year: "2025",
  },
];
